const mongoose = require("mongoose");
const showSchema = mongoose.Schema({
    name:{
        type:String,
        required:true
    },
    date:{
        type:Date,
        required:true
    },
    time:{
        type:String,
        required:true
    },
    movie:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"movies",
        required:true
    },
    ticketPrice:{
        type:String,
        required:true
    },
    totalSeats:{
        type:Number,
        required:true
    },
    bookedSeats:{
        type:Array,
        default:[]
    },
    theatre:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"theatres"
    }
},{
    timestamps:true
});
module.exports = mongoose.model("shows",showSchema);